<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Openinghours
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

?>

<div class="iways-opening">
    <table>
        <?php
        foreach ($block->getOpeningMatrix() as $key => $value) {
            ?>
            <tr>
                <td align="left">
                    <?php echo $key ?>
                </td>
                <td align="right">
                    <?php echo $value ?>
                </td>
            </tr>
            <?php
        }
        ?>
    </table>
</div>
