<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_DeveloperToolBox
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

$adminLink = ($adminUri = $block->getAdminUri()) // todo move this in block ($block->getAdminLink())
             ? '<span><a href="' . $adminUri . '"'
             . '         target="_BLANK">Backend</a></span>'
             : false;

if ($block->showToolbar()) {
    ?>
    <div class="iways-toolbar">
        <?php
        echo $block->getItemsHtml() . $adminLink;
        ?>
    </div>
    <?php
}

?>

<script type="text/javascript">
    require([
        'jquery'
    ], function($)
    {
        if (window.parent == window) {
            $('.iways-toolbar').show();
        }
    });
</script>
