<?php
/**
 * @var \Iways\Slider\Block\Widget\Slider $this
 */
$htmlId = $this->getHtmlId();
?>
<div id="<?php echo $htmlId; ?>"
    class="main-box-full-width-wrapper iways-slider"<?php echo $this->getSliderImage() ? ' style="background-image:url(' . $this->getSliderImage() . ')"' : ''; ?>>
    <ul>
        <?php foreach ($this->getBanners() as $banner) : ?>
            <?php /** @var \Iways\Slider\Model\Banner $banner */ ?>
            <li>
                <div class="main-box-full-width-wrapper">
                    <div class="main-box-wrapper banner-wrapper">
                        <img class="banner-image" src="<?php echo $banner->getImageUrl() ?>"
                             title="<?php echo $banner->getImageAlt(); ?>"/>
                        <div class="banner-content">
                            <h2><?php echo $banner->getTitle(); ?></h2>
                            <p class="banner-description"><?php echo $banner->getContent(); ?></p>
                            <a class="cta-link"
                               href="<?php echo $banner->getCtaLink(); ?>"><?php echo $banner->getCtaTitle(); ?></a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<script type="text/x-magento-init">
{ "#<?php echo $htmlId; ?>":
    {"Iways_Slider/js/slider_widget":
        {"sliderId": "<?php echo $htmlId; ?>"}
    }
}
</script>
