<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_SocialLinks
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

?>

<div class="wrapper">
    <span><?php echo __($block->getBlockTitle()) ?></span>
    <ol>
        <?php
        foreach ($block->getSocialLinks() as $key => $values) {
            ?>
            <li class="iways-<?php echo $key ?>">
                <a href="<?php echo $values['url'] ?>"
                   target="_blank">
                    <?php echo $values['label'] ?>
                </a>
            </li>
            <?php
        }
        ?>
    </ol>
</div>

<br class="clearfix" />
