<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Mobile
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);

$helper = $this->helper('Iways\Design\Helper\Data');
$storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Store\Model\StoreManagerInterface');
$navigationDirection = $helper->getConfig('design/mobile/navigation_direction', $storeManager->getStore()->getCode());
dump($storeManager->getStore()->getCode());
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu": {"responsive": true, "expanded": true, "position": {"my": "left top", "at": "left bottom"}, "invert_direction": <?php echo $navigationDirection ?>}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
    </ul>
</nav>
