<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Design
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

?>

<div class="sidebar title" rel="<?php echo $block->getSidebarType() ?>">
    <div class="sidebar-title">
        <strong><?php echo $block->getData('title') ?></strong>
    </div>
</div>
