<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Base
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

$helper = $this->helper('Iways\Base\Helper\Data');
$currentOrder = $block->getCurrentOrder();

?>

<div class="toolbar-sorter sorter">
    <?php
    if (!$helper->getConfig('iways_base/catalog_category/use_compact_sorter')) {
        ?>
        <label class="sorter-label" for="sorter"><?php echo __('Sort By') ?></label>
        <?php
    }
    ?>
    <select id="sorter"
            data-role="sorter"
            class="sorter-options">
        <?php
        foreach ($block->getAvailableOrders() as $key => $order) {
            ?>
            <option value="<?php echo $key ?>"
                <?php
                if (!$key) {
                    ?>
                    selected="selected" disabled="disabled"
                    <?php
                }
                if (is_string($currentOrder) && ($key == $currentOrder)) {
                    ?>
                    selected="selected"
                    <?php
                }
                ?>
                >
                <?php echo $block->escapeHtml(__($order)) ?>
            </option>
            <?php
        }
    ?>
    </select>
</div>
