<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Design
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

echo $block->addTag(
    'link',
    [
        'rel' => "stylesheet",
        'type' => "text/css",
        'media' => "all",
        'href' => "/pub/media/iways/styles.css",
    ]
); // because of https://magento.stackexchange.com/questions/99239/remove-pub-media-styles-css-from-theme-in-magento-2-0
