<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Base
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

$contents = $block->getData('contents');

$contents = str_replace(
    $block->getData('static_path'),
    $block->getViewFileUrl($block->getData('view_path')),
    $contents
);

$parse_down = new Parsedown();
$parse_down->setBreaksEnabled(true);
$contents = $parse_down->text($contents);

$images_path = 'Iways_Base/images/documentation/';

$markdown_url = $block->getViewFileUrl($images_path . 'logo_markdown.png');

?>

<div class="iways-documentation">
    <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet"
       target="_blank">
        <img src="<?php echo $markdown_url ?>"
             alt="MarkDown"
             title="MarkDown"
             class="logo markdown" />
    </a>

    <?php
    if ($block->getData('locale')) {
        $image_url = $block->getViewFileUrl(
            $images_path
            . $block->getData('locale')
            . '/language_flag.png'
        );
        ?>
        <span class="language-flag">
            <img src="<?php echo $image_url ?>"
                 alt="<?php echo $block->getData('locale') ?>"
                 title="<?php echo $block->getData('locale') ?>" />
        </span>
        <?php
    }

    echo $contents;
    ?>
</div>
