<?php

/**
 * Ⓒ i-ways sales solutions GmbH
 *
 * PHP Version 5
 *
 * @category File
 * @package  Iways_Base
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://www.i-ways.net
 */

?>

<nav data-mage-init='{"globalNavigation": {}}'
     class="admin__menu">
    <?php echo $block->renderNavigation($block->getMenuModel(), 0, 13) ?>
</nav>
