<fieldset>
    <legend><?php echo __('Colors') ?></legend>
    <span class="theme-color background-color" style="width:99.666%"><?php echo __('Text color on background color') ?></span>
    <br />
    <span class="theme-color primary-color-lighter"><?php echo __('Primary color lighter') ?></span>
    <span class="theme-color primary-color-light"><?php echo __('Primary color light') ?></span>
    <span class="theme-color primary-color"><?php echo __('Primary color') ?></span>
    <span class="theme-color primary-color-dark"><?php echo __('Primary color dark') ?></span>
    <span class="theme-color primary-color-darker"><?php echo __('Primary color darker') ?></span>
    <br />
    <span class="theme-color secondary-color-lighter"><?php echo __('Secondary color lighter') ?></span>
    <span class="theme-color secondary-color-light"><?php echo __('Secondary color light') ?></span>
    <span class="theme-color secondary-color"><?php echo __('Secondary color') ?></span>
    <span class="theme-color secondary-color-dark"><?php echo __('Secondary color dark') ?></span>
    <span class="theme-color secondary-color-darker"><?php echo __('Secondary color darker') ?></span>
    <br />
    <span class="theme-color tertiary-color-lighter"><?php echo __('Tertiary color lighter') ?></span>
    <span class="theme-color tertiary-color-light"><?php echo __('Tertiary color light') ?></span>
    <span class="theme-color tertiary-color"><?php echo __('Tertiary color') ?></span>
    <span class="theme-color tertiary-color-dark"><?php echo __('Tertiary color dark') ?></span>
    <span class="theme-color tertiary-color-darker"><?php echo __('Tertiary color darker') ?></span>
    <br />
    <span class="theme-color grey-lighter"><?php echo __('Grey lighter') ?></span>
    <span class="theme-color grey-light"><?php echo __('Grey light') ?></span>
    <span class="theme-color grey-normal"><?php echo __('Grey normal') ?></span>
    <span class="theme-color grey-dark"><?php echo __('Grey dark') ?></span>
    <span class="theme-color grey-darker"><?php echo __('Grey darker') ?></span>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __('Headlines') ?></legend>
    <h1 class="display">Headline tag H1.display</h1>
    <h1>Headline tag H1</h1>
    <h2>Headline tag H2</h2>
    <h3>Headline tag H3</h3>
    <h4>Headline tag H4</h4>
    <h5>Headline tag H5</h5>
    <h5 class="muted">Headline tag H5.muted</h5>
    <h6>Headline tag H6</h6>
    <h6 class="muted">Headline tag H6.muted</h6>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __('Text elements') ?></legend>
    <p class="lead">
        Paragraph tag P.lead:
    </p>
    <p>
        Paragraph tag P: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id fringilla lacus. Maecenas nisi mi, suscipit in consequat id, tempus sed orci.<br />
    </p>
    <p>
        <big>Paragraph tag P + BIG: Maecenas quis ante gravida ex lacinia ultrices.</big>
    </p>
    <p>
        <small>Paragraph tag P + SMALL: Curabitur ultricies dignissim cursus.</small>
    </p>
    <p>
        <blockquote>Paragraph tag P + BLOCKQUOTE: Mauris lacinia pellentesque ex, id blandit tortor ornare sed.</blockquote>
        <em>Paragraph tag P + EM</em>
    </p>
    <p>
        Aenean blandit sapien sit amet dui tincidunt mattis. <strong>Paragraph tag P + STRONG: Integer congue dictum porta. Quisque convallis suscipit diam non faucibus.</strong>
    </p>
    <strong>Text tag STRONG</strong><br />
    <b>Text tag B</b><br />
    <blockquote>
        Text tag BLOCKQUOTE<br />
        <small><em>Text tag SMALL + EM</em></small>
    </blockquote>
    <big>Text tag BIG</big><br />
    <small>Text tag SMALL</small><br />
    <em>Text tag EM</em><br />
    <i>Text tag I</i><br />
    <a>Anchor tag A</a><br />
    <ul>
        <li>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
        </li>
        <li>
            <p>
                Sed id fringilla lacus.
            </p>
            <ul>
                <li>
                    <p>
                        Maecenas nisi mi, suscipit in consequat id, tempus sed orci.
                    </p>
                </li>
                <li>
                    <p>
                        Maecenas quis ante gravida ex lacinia ultrices.
                    </p>
                </li>
            </ul>
        </li>
        <li>
            <p>
                Curabitur ultricies dignissim cursus.
            </p>
            <ul>
                <li>
                    <p>
                        Mauris lacinia pellentesque ex, id blandit tortor ornare sed.
                    </p>
                </li>
                <ul>
                    <li>
                        <p>
                            Aenean blandit sapien sit amet dui tincidunt mattis.
                        </p>
                    </li>
                    <li>
                        <p>
                            Integer congue dictum porta.
                        </p>
                    </li>
                    <li>
                        <p>
                            Quisque convallis suscipit diam non faucibus.
                        </p>
                    </li>
                </ul>
            </ul>
         </li>
    </ul>
    <ol>
        <li>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
        </li>
        <li>
            <p>
                Sed id fringilla lacus.
            </p>
            <ol>
                <li>
                    <p>
                        Maecenas nisi mi, suscipit in consequat id, tempus sed orci.
                    </p>
                </li>
                <li>
                    <p>
                        Maecenas quis ante gravida ex lacinia ultrices.
                    </p>
                </li>
            </ol>
        </li>
        <li>
            <p>
                Curabitur ultricies dignissim cursus.
            </p>
            <ol>
                <li>
                    <p>
                        Mauris lacinia pellentesque ex, id blandit tortor ornare sed.
                    </p>
                </li>
                <ol>
                    <li>
                        <p>
                            Aenean blandit sapien sit amet dui tincidunt mattis.
                        </p>
                    </li>
                    <li>
                        <p>
                            Integer congue dictum porta.
                        </p>
                    </li>
                    <li>
                        <p>
                            Quisque convallis suscipit diam non faucibus.
                        </p>
                    </li>
                </ol>
            </ol>
         </li>
    </ol>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __('Widgets') ?></legend>
    <button class="light small">
        <span><?php echo __('Small light button') ?></span>
    </button>
    <button class="light">
        <span><?php echo __('Normal light button') ?></span>
    </button>
    <button class="light big">
        <span><?php echo __('Big light button') ?></span>
    </button>
    <br />
    <button class="dark small">
        <span><?php echo __('Small dark button') ?></span>
    </button>
    <button class="dark">
        <span><?php echo __('Normal dark button') ?></span>
    </button>
    <button class="dark big">
        <span><?php echo __('Big dark button') ?></span>
    </button>
    <br />
    <form>

    </form>
</fieldset>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $('fieldset > .theme-color').each(function() {
            var html = $(this).html(),
                background_color = $(this).css('background-color');
            if (background_color == 'rgba(0, 0, 0, 0)')
                $(this).hide();
            else
            	$(this).html(html + '<br />' + background_color);
        });
    });
</script>
