<?php
$message = $block->returnSmth();
?>
<div class="layout-wrapper layout-1">
    <div class="top back"></div>
    <div class="bottom">
        <div class="container-1 back"></div>
        <div class="container-2 back"></div>
        <div class="container-3 back"></div>
        <div class="container-4 back"></div>
        <div class="container-5 back"></div>
    </div>
</div>
<div class="layout-wrapper layout-4" style="display: none;">
    <div class="top back"></div>
    <div class="bottom">
        <div class="left">
            <div class="container-1 back"></div>
            <a href="http://www.youtube.de/" class="container-2 back"></a>
        </div>
        <div class="right">
            <div class="container-3 back"></div>
            <div class="container-4 back"></div>
            <div class="container-5 back"></div>
        </div>
    </div>
</div>
